name: release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: pio
          path: |
            ~/.cache/pip
            ~/.platformio/.cache

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
      # - name: Publish
      #   run: |
      #     pio account login
      #     pio package publish .
      #   env:
      #     PATH: /home/runner/.platformio/penv/bin
